### ISSUE TITLE
Improve noble benchmarks

### ISSUE THREAD

**Issue by paulmillr** [hazae41/ed25519-dalek-wasm#1]
First call of ed25519 does table precomputation. That's why it takes 30ms and not 1ms.

You can do it manually: `ed.utils.precompute(8)` or just call `getPublicKey` once somewhere else.

I think it makes sense to move it out of benchmarks to initialization. After all, you don't measure wasm init time.

**Comment by hazae41** [comment]
Thanks, will fix it ASAP

Keep up the good work on Noble!

**Comment by paulmillr** [comment]
Also maybe switch to [noble-curves](https://github.com/paulmillr/noble-curves) instead, single-pkg ed is going in a different direction now:

```ts
import { ed25519 } from '@noble/curves/ed25519';
```
